version: "3.7"

services:
  database:
    image: postgres
    container_name: database_theproject
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=theproject
      - POSTGRES_DB=theproject
    volumes:
      - pgdata:/data/postgres
    network_mode: host
volumes:
  pgdata:
    driver: local
